### ISSUE TITLE
Loading wheel enhanchements

### ISSUE THREAD

**Issue by rogerburks** [chalcid/ucd_website#78]
- Add more loading wheels to other searches (SourcesSearch, others?).

- Improve loading wheel occurrence, so that it is seen as soon as it should be.

- Make the loading wheel look better.

**Comment by rogerburks** [comment]
Fixed with #102 . #103, #104

**Comment by arpanakriti95-rgb** [comment]
The contents of the search are not loading or opening.

**Comment by rogerburks** [comment]
> The contents of the search are not loading or opening.

Hello! Please provide a link of what is not opening. My test search is working.

**Comment by arpanakriti95-rgb** [comment]
https://ucd.chalcid.org/#/taxon?taxonID=463508

**Comment by rogerburks** [comment]
> https://ucd.chalcid.org/#/taxon?taxonID=463508

Hi, this works for me. It must be something happening with your access or browser.

<img width="1016" height="567" alt="Image" src="https://github.com/user-attachments/assets/ab5bb2a7-159e-46b4-88e4-c625dfafab86" />

**Comment by arpanakriti95-rgb** [comment]
<img width="1912" height="897" alt="Image" src="https://github.com/user-attachments/assets/a5b66811-0c84-4954-b46f-f0ce95b6df75" />
Hi! the contents under the hyperlinks like show topic references are not opening also the world map.

**Comment by rogerburks** [comment]
That would be a data curation issue (see https://github.com/chalcid/ucd/issues for reporting that).
