### ISSUE TITLE
Invalid values in API calls

### ISSUE THREAD

**Issue by LocoDelAssembly** [chalcid/ucd_website#84]
We have been errors notifications from SFG servers because of some malformed API queries coming form here.

Some examples:

* https://sfg.taxonworks.org/api/v1/asserted_distributions?taxon_name_id[]=[object+Object]&extend[]=geographic_area&extend[]=citations&per=10000&descendants=true&project_token=adhBi59dc13U7RxbgNE5HQ
* https://sfg.taxonworks.org/api/v1/biological_associations?taxon_name_id[]=[object+Object]&extend[]=object&extend[]=subject&extend[]=biological_relationship&extend[]=taxonomy&extend[]=biological_relationship_types&extend[]=citations&extend[]=source&per=10000&descendants=true&project_token=adhBi59dc13U7RxbgNE5HQ

The problem is those `[object+Object]` values which are supposed to be integer.

I couldn't gather sufficient information to tell which species are causing this problem. Browsed the site for a bit but couldn't trigger the problem myself.

**Comment by rogerburks** [comment]
Hi Hernán! Yes that was entirely due to an error that I was causing while testing. The problem was that I was trying to extract string values from `taxon_name` objects, but I was mistakenly referencing an object inside it instead of the string value. This caused the bad calls that you describe. I will check things out to see if it is still happening, but I had thought I had fixed that previously. 

This would be something that the Taxon Page component would be causing due to improper formation of `taxonIDChain` to generate props for the child components. My expectation is that the child components would fail to load properly when the problem occurs. This should hopefully only be happening from my local dev server and not from the live site.

Thanks again for pointing this out!

**Comment by rogerburks** [comment]
I see the problem. In my refactor of `taxonID` I failed to refactor it to `taxonID.value` for some calls. Referencing `taxonID` now references an object, when I need to reference `taxonID.value` to get the desired string. Fixing this now.

**Comment by LocoDelAssembly** [comment]
I believe calls from from real site unless your local env emulates real visit when hitting the API:

```
    * HTTP_ACCEPT_LANGUAGE                                    : fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7
    * HTTP_HOST                                               : sfg.taxonworks.org
    * HTTP_ORIGIN                                             : https://ucd.chalcid.org/
    * HTTP_REFERER                                            : https://ucd.chalcid.org/
    * HTTP_SEC_CH_UA                                          : "Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126"
    * HTTP_SEC_CH_UA_MOBILE                                   : ?0
    * HTTP_SEC_CH_UA_PLATFORM                                 : "Windows"
    * HTTP_SEC_FETCH_DEST                                     : empty
    * HTTP_SEC_FETCH_MODE                                     : cors
    * HTTP_SEC_FETCH_SITE                                     : cross-site
    * HTTP_USER_AGENT                                         : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
    * HTTP_VERSION                                            : HTTP/1.1
    * HTTP_X_FORWARDED_FOR                                    : 93.22.XXX.XX,10.44.0.0
```

**Comment by rogerburks** [comment]
Yes that is exactly correct. The main culprit on the live site seems to be calls to `data_attributes` to generate type specimen information.

**Comment by rogerburks** [comment]
I am hoping that #85 fixes that in the live site now, but please let me know if the problem persists (or if I accidentally broke something else). Thanks again!

**Comment by rogerburks** [comment]
Now I think it is fixed. Leaving this open for the weekend just in case I didn't do something right (I think my coffee had not kicked in this morning).
